/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ITodo } from "./components/types";
export namespace Components {
    interface AppHome {
    }
    interface ListTodo {
        "todos": Array<ITodo>;
    }
    interface MyButton {
        "text": string;
    }
    interface ToDo {
        "todo": ITodo;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLListTodoElement extends Components.ListTodo, HTMLStencilElement {
    }
    var HTMLListTodoElement: {
        prototype: HTMLListTodoElement;
        new (): HTMLListTodoElement;
    };
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLToDoElement extends Components.ToDo, HTMLStencilElement {
    }
    var HTMLToDoElement: {
        prototype: HTMLToDoElement;
        new (): HTMLToDoElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "list-todo": HTMLListTodoElement;
        "my-button": HTMLMyButtonElement;
        "to-do": HTMLToDoElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface ListTodo {
        "todos"?: Array<ITodo>;
    }
    interface MyButton {
        "text"?: string;
    }
    interface ToDo {
        "onUpdate-todo"?: (event: CustomEvent<ITodo>) => void;
        "todo"?: ITodo;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "list-todo": ListTodo;
        "my-button": MyButton;
        "to-do": ToDo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "list-todo": LocalJSX.ListTodo & JSXBase.HTMLAttributes<HTMLListTodoElement>;
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "to-do": LocalJSX.ToDo & JSXBase.HTMLAttributes<HTMLToDoElement>;
        }
    }
}
