/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ITodo } from "./components/types";
export namespace Components {
    interface AddTodo {
    }
    interface AppHome {
    }
    interface EditTodo {
        "todo": ITodo;
    }
    interface ListTodo {
        "todos": Array<ITodo>;
    }
    interface ToDo {
        "todo": ITodo;
    }
}
declare global {
    interface HTMLAddTodoElement extends Components.AddTodo, HTMLStencilElement {
    }
    var HTMLAddTodoElement: {
        prototype: HTMLAddTodoElement;
        new (): HTMLAddTodoElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLEditTodoElement extends Components.EditTodo, HTMLStencilElement {
    }
    var HTMLEditTodoElement: {
        prototype: HTMLEditTodoElement;
        new (): HTMLEditTodoElement;
    };
    interface HTMLListTodoElement extends Components.ListTodo, HTMLStencilElement {
    }
    var HTMLListTodoElement: {
        prototype: HTMLListTodoElement;
        new (): HTMLListTodoElement;
    };
    interface HTMLToDoElement extends Components.ToDo, HTMLStencilElement {
    }
    var HTMLToDoElement: {
        prototype: HTMLToDoElement;
        new (): HTMLToDoElement;
    };
    interface HTMLElementTagNameMap {
        "add-todo": HTMLAddTodoElement;
        "app-home": HTMLAppHomeElement;
        "edit-todo": HTMLEditTodoElement;
        "list-todo": HTMLListTodoElement;
        "to-do": HTMLToDoElement;
    }
}
declare namespace LocalJSX {
    interface AddTodo {
        "onAdd-more"?: (event: CustomEvent<string>) => void;
    }
    interface AppHome {
    }
    interface EditTodo {
        "onEdit-todo"?: (event: CustomEvent<ITodo>) => void;
        "todo"?: ITodo;
    }
    interface ListTodo {
        "todos"?: Array<ITodo>;
    }
    interface ToDo {
        "onDelete-todo"?: (event: CustomEvent<ITodo>) => void;
        "onUpdate-todo"?: (event: CustomEvent<ITodo>) => void;
        "todo"?: ITodo;
    }
    interface IntrinsicElements {
        "add-todo": AddTodo;
        "app-home": AppHome;
        "edit-todo": EditTodo;
        "list-todo": ListTodo;
        "to-do": ToDo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-todo": LocalJSX.AddTodo & JSXBase.HTMLAttributes<HTMLAddTodoElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "edit-todo": LocalJSX.EditTodo & JSXBase.HTMLAttributes<HTMLEditTodoElement>;
            "list-todo": LocalJSX.ListTodo & JSXBase.HTMLAttributes<HTMLListTodoElement>;
            "to-do": LocalJSX.ToDo & JSXBase.HTMLAttributes<HTMLToDoElement>;
        }
    }
}
